[package]
name = "memex-cef"
publish = false
edition = "2024"

[dependencies]
cef.workspace = true
async-channel.workspace = true
async-io.workspace = true
futures.workspace = true
log.workspace = true
raw-window-handle.workspace = true
anyhow.workspace = true
