[package]
name = "memex-app"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
gpui = "0.2.2"
gpui-component = "0.3.1"
rust-embed = "8.8.0"
uuid = { version = "1.18.1", features = ["v4"] }
